language: python
python:
  - "3.5"

install: make init
script: ./scripts/test.sh

after_success:
  #  - . ./p3_5env/bin/activate
  - coveralls

notifications:
  slack:
    rooms:
      - virginia-tech-sailbot:7TUtMKl4iXUIRxEy0YAhrsVk#boat-programming
