language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_install:
  - make test
  - docker ps -a
  # - make test_remote_img

after_success:
  #  - . ./p3_5env/bin/activate
  - coveralls

notifications:
  slack:
    rooms:
      - virginia-tech-sailbot:7TUtMKl4iXUIRxEy0YAhrsVk#boat-programming
