language: python
python:
  - "3.5"

# Assumes latest beaglebone-base image is pushed onto docker.
script: make test
after_success:
  - coveralls

notifications:
  slack:
    rooms:
      - virginia-tech-sailbot:7TUtMKl4iXUIRxEy0YAhrsVk#boat-programming
