language: python
python:
  - "3.5"

install: docker run --rm --privileged hypriot/qemu-register
script: make build
after_success:
#  - . ./p3_5env/bin/activate
  - coveralls

notifications:
  slack:
    rooms:
      - virginia-tech-sailbot:7TUtMKl4iXUIRxEy0YAhrsVk#boat-programming
