FROM balenalib/beaglebone-black-debian-python

ENV HOSTNAME beaglebone

RUN apt-get -y update && apt-get -y install make wget

COPY scripts /sailbot/scripts
COPY Makefile /sailbot/
COPY requirements.prod.txt /sailbot/
WORKDIR /sailbot

RUN make init

COPY src /sailbot/src
COPY tests /sailbot/tests
COPY main.py /sailbot/main.py
