FROM balenalib/beaglebone-black-debian:stretch-build

ENV HOSTNAME beaglebone
ENV UDEV=1

ENV LANG C.UTF-8

RUN [ "cross-build-start" ]

RUN apt-get -y update && apt-get -y install make wget

ENTRYPOINT ["/usr/bin/entry.sh"]

COPY scripts /sailbot/scripts
COPY tests /sailbot/tests
COPY Makefile /sailbot/
COPY requirements.prod.txt /sailbot/
WORKDIR /sailbot

RUN make _init

COPY src /sailbot/src
COPY main.py /sailbot/main.py

RUN [ "cross-build-end" ]
