FROM balenalib/beaglebone-black-debian:stretch-build

ENV HOSTNAME beaglebone
ENV UDEV=1

ENV LANG C.UTF-8

RUN apt-get update

ENTRYPOINT ["/usr/bin/entry.sh"]

COPY scripts /sailbot/scripts
COPY tests /sailbot/tests
COPY Makefile /sailbot/
COPY requirements.prod.txt /sailbot/
WORKDIR /sailbot

RUN make _init

COPY src /sailbot/src
COPY main.py /sailbot/main.py
