FROM debian:stretch

# Settings env variables
ENV HOSTNAME debian-stretch

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

# Installing useful packages
RUN apt-get update && apt-get install -y --no-install-recommends \
        make \
        wget \
        git \
        cmake \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

# Installing python development tools
# > It may be beneficial to specify versions of python & pip here.
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        python3-wheel \
        python3-setuptools \
        python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Updating pip to latest version
RUN pip3 install --upgrade pip

# set PYTHONPATH to point to site-packages
ENV PYTHONPATH /usr/local/lib/python3.5/site-packages

# Caching these layers to improve build time for larger packages.
# -----------------------------------------------------
# > Add additional packages here on separate RUN lines
# > to cache larger installation steps into docker daemon

# Installing numpy, scipy, and opencv
RUN pip3 install opencv-python
RUN pip3 install numpy
RUN pip3 install scipy

# Installing filterpy
RUN apt-get update && apt-get install -y --no-install-recommends \
        pkg-config \
        libfreetype6-dev \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install filterpy

# Installing base requirements
COPY requirements.base.txt /sailbot/
RUN pip3 install -r /sailbot/requirements.base.txt

# Installing Adafruit_BBIO
RUN wget https://files.pythonhosted.org/packages/53/2b/b0e3dce6113225aae9beb886b2addd4fd5c140ba93c9503d7e4a97021bcc/Adafruit_BBIO-1.1.1.tar.gz \
    && tar -xf Adafruit_BBIO-1.1.1.tar.gz \
    && cd Adafruit_BBIO-1.1.1 \
    && python3.5 setup.py install \
    && cd .. \
    && rm -rf Adafruit_BBIO-1.1.1*

# -----------------------------------------------------

# Cleanup unused dependencies and make log directory
RUN apt-get autoremove \ 
    && mkdir -p /sailbot/logs

WORKDIR /sailbot

# Installing development requirements
COPY requirements.dev.txt ./

RUN pip3 install -r requirements.dev.txt

# Copying source files to image
COPY scripts ./scripts
COPY tests ./tests
COPY Makefile main.py ./
COPY src ./src
