FROM balenalib/beaglebone-black-debian-python

ENV HOSTNAME beaglebone
ENV UDEV=1

ENTRYPOINT ["/usr/bin/entry.sh"]

RUN apt-get -y update && apt-get -y install make wget

COPY scripts /sailbot/scripts
COPY Makefile /sailbot/
COPY requirements.prod.txt /sailbot/
WORKDIR /sailbot

RUN make _init

COPY src /sailbot/src
COPY tests /sailbot/tests
COPY main.py /sailbot/main.py
