FROM balenalib/beaglebone-black-debian:stretch-build

ENV HOSTNAME beaglebone
ENV UDEV=1

ENV LANG C.UTF-8

ENTRYPOINT ["/usr/bin/entry.sh"]

RUN apt-get update && apt-get install -y

COPY scripts /sailbot/scripts
COPY Makefile /sailbot/
COPY requirements.prod.txt /sailbot/
WORKDIR /sailbot

RUN make _init

COPY src /sailbot/src
COPY main.py /sailbot/main.py
